// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MatcherController from "./matcher_controller"
application.register("matcher", MatcherController)

import ConsolidatorController from "./consolidator_controller"
application.register("consolidator", ConsolidatorController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import UnitsController from "./units_controller"
application.register("units", UnitsController)
