services:

  #  web:
  #    build: .
  ##    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
  #    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
  #    volumes:
  #      - .:/usr/src/app
  #      - bundle:/usr/local/bundle
  #    ports:
  #      - "3001:3000"
  #    env_file:
  #      - .env
  #    environment:
  #      - HISTFILE=/usr/src/app/log/.bash_history
  #    depends_on:
  #      - mariadb

  #  mariadb:
  #    image: mariadb:10
  #    restart: always
  #    environment:
  #      MARIADB_ROOT_PASSWORD: mariapass
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - ./mysqldev:/var/lib/mysql
  #      - ./mysqldev-cnf:/etc/mysql/conf.d
  #      - ./mysqldev-enc:/etc/mysql/encryption

  elasticsearch:
    image: elasticsearch:7.17.7
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.8
    ports:
      - "5601:5601"
    extra_hosts:
      #     - "elasticsearch:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'

#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

#  redis:
#    image: redis
#    volumes:
#      - redis_data:/data
#  solr:
#    image: solr
#    ports:
#      - "8983:8983"
#    volumes:
#      - ./solr:/var/solr
#    command:
#      - solr-precreate
#      - development

#volumes:
#  bundle:
