require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/source_lookups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SourceLookup. As you add validations to SourceLookup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SourceLookup.create! valid_attributes
      get source_lookups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      source_lookup = SourceLookup.create! valid_attributes
      get source_lookup_url(source_lookup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_source_lookup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      source_lookup = SourceLookup.create! valid_attributes
      get edit_source_lookup_url(source_lookup)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SourceLookup" do
        expect {
          post source_lookups_url, params: { source_lookup: valid_attributes }
        }.to change(SourceLookup, :count).by(1)
      end

      it "redirects to the created source_lookup" do
        post source_lookups_url, params: { source_lookup: valid_attributes }
        expect(response).to redirect_to(source_lookup_url(SourceLookup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SourceLookup" do
        expect {
          post source_lookups_url, params: { source_lookup: invalid_attributes }
        }.to change(SourceLookup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post source_lookups_url, params: { source_lookup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested source_lookup" do
        source_lookup = SourceLookup.create! valid_attributes
        patch source_lookup_url(source_lookup), params: { source_lookup: new_attributes }
        source_lookup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the source_lookup" do
        source_lookup = SourceLookup.create! valid_attributes
        patch source_lookup_url(source_lookup), params: { source_lookup: new_attributes }
        source_lookup.reload
        expect(response).to redirect_to(source_lookup_url(source_lookup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        source_lookup = SourceLookup.create! valid_attributes
        patch source_lookup_url(source_lookup), params: { source_lookup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested source_lookup" do
      source_lookup = SourceLookup.create! valid_attributes
      expect {
        delete source_lookup_url(source_lookup)
      }.to change(SourceLookup, :count).by(-1)
    end

    it "redirects to the source_lookups list" do
      source_lookup = SourceLookup.create! valid_attributes
      delete source_lookup_url(source_lookup)
      expect(response).to redirect_to(source_lookups_url)
    end
  end
end
