---
engine_version: 0.2.72
file_version: 2022-09-07 08:32:04.313084000 Z
resources:
- name: match
  preferences:
    columns:
    - name: matched_articles_count
      display_name: matched_articles_count
      column_type: integer
      access_type: read_write
      virtual: true
      format: {}
      validators: []
      description: Number of articles in match
    - name: matched_articles
      display_name: matched_articles_count
      column_type: integer
      access_type: hidden
      virtual: true
      format: {}
      validators: []
      description: Number of articles in match
  updated_at: 2022-08-23 17:46:13.156421000 +00:00
configs:
- key: header.links
  value: []
  updated_at: 2022-09-07 08:32:04.313084000 +00:00
- key: resources.match.columns.order
  value:
  - id
  - status
  - matched_articles_count
  - updated_at
  - created_at
  updated_at: 2022-08-23 17:45:59.896734000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2022-08-29 11:29:30.258404000 +00:00
